<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Arte dos livros</title>
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/estilo.css">
         <script src="js/codigo.js"></script>
        <link rel="icon" type="favicon/png" href="https://img.icons8.com/ios-glyphs/30/000000/book.png"/>
    </head>
    <body>
