<form action="cadastro_cliente.php" method="POST">
    <center><h3 class="transf">Informe os dados baixo:</h3></center>
    <div class=" container alinhar">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Primeiro nome:</label>
                <input type="text" class="form-control" name="primeiro_nome">
            </div>
            <div class="form-group col-md-6">
                <label>Último nome:</label>
                <input type="text" class="form-control" name="ultimo_nome">
            </div>
        </div>