<main class="bd-masthead" id="content" role="main">
    <div class="container">
        <div class="row">
            <div class="col-5 mx-auto col-md-5 order-md-1 imagem">
                <img src="https://img.icons8.com/clouds/500/000000/book.png"/>
            </div>
            <div class="col-md-7 order-md-2 text-center text-md-center pr-md-8 texto_inicial_2">
                <h1 class="mb-2">Arte dos Livros!</h1>
                <p class="lead mb-3">
                    Para lhe ajudar a navegar, mostramos algumas opções.
                </p>
                <div class="mb-2">
                    <a class="btn btn-primary" href="cadastro_cliente.php" role="button">Cadastro de Cliente</a>
                    <a class="btn btn-primary" href="consulta_cliente.php" role="button">Consulta de Cliente</a>
                    <a class="btn btn-primary" href="cadastro_livro.php" role="button">Cadastro de Livro</a>
                </div>
                <a class="btn btn-primary" href="consulta_livro.php" role="button">Consulta de Livro</a>
                <a class="btn btn-primary" href="consulta_nome_livro.php" role="button">Consulta de Livro por Nome</a>
            </div>
        </div>
    </div>
</main>
